import { Component, OnInit } from '@angular/core';
import { AppShellComponent } from './layout';
import { Amplify } from 'aws-amplify';

@Component({
  selector: 'app-root',
  standalone: true,
  template: '<app-shell></app-shell>',
  styles: [],
  imports: [AppShellComponent],
})
export class AppComponent implements OnInit {
  title = 'pet-genie';

  async ngOnInit(): Promise<void> {
    try {
      // Dynamically import amplify outputs (generated by Amplify sandbox)
      const outputs = await import('../../amplify_outputs.json');
      Amplify.configure(outputs.default || outputs);
    } catch (error) {
      console.warn('Amplify outputs not found. Run `npx ampx sandbox` to generate.');
    }
  }
}
